#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
set +e
brew bundle
set -e

# find the installers and run them iteratively
# Don't use set -e here since some installers may fail gracefully
for installer in $(find . -name install.sh); do
    echo "› ${installer}"
    set +e
    sh "${installer}"
    set -e || true
done
